name: Python CI

on:
  push:
    branches:
      - user-story2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/test_nucleotide_count.py
          pytest tests/test_multiline_nucleotide_count.py

      - name: Merge branch to main
        run: |
          git fetch
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          git checkout main
          git merge -X theirs user-story2 --allow-unrelated-histories

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git push origin main
          git push origin --delete user-story2